[build-system]
requires = ["scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "sekai-deck-recommend-cpp"
version = "0.1.13"

[tool.scikit-build]
cmake.args = ["-DCMAKE_BUILD_TYPE=Release"]